version: '3.5'

services:
  producer:
    container_name: 'producer'
    image: 'producer'
    ports:
      - "8080:8080"
    depends_on:
      - kafka
      - zookeeper
    environment:
      - SERVER=kafka:9092

  consumer:
    container_name: 'consumer'
    image: 'consumer'
    depends_on:
      - kafka
      - zookeeper
    environment:
      - SERVER=kafka:9092

  zookeeper:
    container_name: 'zookeeper'
    image: 'bitnami/zookeeper:latest'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    container_name: 'kafka'
    image: 'bitnami/kafka:latest'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_LISTENERS=PLAINTEXT://:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CREATE_TOPICS="users"
    depends_on:
      - zookeeper
